version: '3'
services:
  api:
    build:
      context: ./src/
      dockerfile: Dockerfile
    volumes:
      - ./src/:/app/src/
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      FLASK_DEBUG: 1
  webserver:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/


