version: '3'

services:

  api:
    environment:
      FLASK_APP: app
    container_name: api
    restart: unless-stopped
    build: ./Api
    volumes:
      - ./Api:/app/src
    networks:
      - apinetwork
    ports:
      - "6000:6000"

  front:
    environment:
      FLASK_APP: app
    container_name: front
    restart: unless-stopped
    build: ./FrontBack
    volumes:
      - ./FrontBack:/app/src
    networks:
      - apinetwork
    ports:
      - "5000:5000"

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    networks:
      - apinetwork
    ports:
      - "8000:8080"

  db:
    image: mariadb
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: Clientes
    volumes:
      - databases:/var/lib/mysql
      - ./db/clientes.sql:/docker-entrypoint-initdb.d/clientes.sql
    networks:
      - apinetwork

networks:
  apinetwork:

volumes:
  databases:
