version: '3'

services:

  api:
    container_name: flask_api
    restart: always
    build: ./src
    volumes:
      - ./src:/app/src
    networks:
      - apinetwork
    expose:
      - "5000"
    ports:
      - "5000:5000"

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    networks:
      - apinetwork
    expose:
      - "8080"
    ports:
      - "8000:8080"

  db:
    image: mariadb
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: Clientes
    volumes:
      - databases:/var/lib/mysql
      - ./db/clientes.sql:/docker-entrypoint-initdb.d/clientes.sql
    networks:
      - apinetwork

networks:
  apinetwork:

volumes:
  databases:
